### ISSUE TITLE
Oklab?

### ISSUE THREAD

**Issue by zevv** [treeform/chroma#21]
Hi there Treeform,

You probably know about this one already, but in case you don't: https://bottosson.github.io/posts/oklab/

**Comment by treeform** [comment]
I did not know about this one. I like it that its so mathematically simple but still gives you the good bits from CIELAB and derivatives.

**Comment by treeform** [comment]
Was added: https://github.com/treeform/chroma/pull/22

Thank you for the issue and the PR!
