### ISSUE TITLE
`spin` func bug 

### ISSUE THREAD

**Issue by hamidb80** [treeform/chroma#26]
hey, first of all I appreciate your work for Nim community. you made dozens of useful libraries.

i have a sample image named `sample.png`: [the background is transparent]
![image](https://user-images.githubusercontent.com/33871336/121774960-12752000-cb9a-11eb-97f9-2d841b7990ec.png)

**here's my code**:
```nim
import pixie, chroma

var img = readImage("./sample.png")

func reverse(clr: Color, reverseAlpha = false): Color=
  Color(
    r: 255 - clr.r,
    g: 255 - clr.g, 
    b: 255 - clr.b,
    a: if reverseAlpha: 1 - clr.a else: clr.a)

for i in 0..<img.data.len:
  template clr: untyped = img.data[i]
  # clr = clr.asColor.spin(0).asRgbx # 1
  # clr = clr.asColor.reverse.asRgbx # 2
  # clr = clr.asColor.reverse.spin(0).asRgbx # 3

img.writeFile("./res.png")
```

1. if I comment out the first commented line [`#1`] I get the same image: [which is obviously correct - it spins the colors 0 degrees]

2. if I comment out [`#2`] i get this: [which is correct]
![image](https://user-images.githubusercontent.com/33871336/121775065-929b8580-cb9a-11eb-94ef-db6d82ee9610.png)

3. however, if i comment out [`#3`] i get this: [which is strange]:
![image](https://user-images.githubusercontent.com/33871336/121775090-beb70680-cb9a-11eb-928d-985f9640ce60.png)

---------------------

I'm really not sure if it's a bug or not, please tell me if I did anything wrong

**Comment by treeform** [comment]
The number space for color is Color float32 0.0-1.0 not uint8 0-255 that's ColorRGBA.

This produces the same output for `.reverse` and `.reverse.spin(0)`

```nim
import pixie, chroma

var img = readImage("./sample.png")

func reverse(clr: Color, reverseAlpha = false): Color =
  Color(
    r: 1.0 - clr.r,
    g: 1.0 - clr.g,
    b: 1.0 - clr.b,
    a: if reverseAlpha: 1 - clr.a else: clr.a
  )

for i in 0..<img.data.len:
  template clr: untyped = img.data[i]
  # clr = clr.asColor.spin(0).asRgbx # 1
  #clr = clr.asColor.reverse.asRgbx # 2
  clr = clr.asColor.reverse.spin(0).asRgbx # 3

img.writeFile("./res.png")
```

**Comment by treeform** [comment]
I don't think you where getting correct reverse values before, this is how reverse should look?
![res](https://user-images.githubusercontent.com/125948/121783521-f0f94180-cb63-11eb-9915-e672ba1e0174.png)

**Comment by hamidb80** [comment]
> I don't think you where getting correct reverse values before, this is how reverse should look?

haha, to be honest that was background theme of my vscode.

**Comment by treeform** [comment]
> background theme of my vscode

Oh that makes sense :)
