### ISSUE TITLE
feature: Grayscale

### ISSUE THREAD

**Issue by ingoogni** [treeform/chroma#28]
Support for grey / grayscale uint8, 16, 32, float 32 [0, 1] & alpha

transformations, conversion to: greyscale
 equal weight        1/3 * r + 1/3 * g + 1/3 * b
 ITU-R BT.709 (HDTV) 0.21 * r + 0.72 * g + 0.07 * b
 ITU-R BT.601 (PAL)  0.299 * r + 0.587 * g + 0.114 * b
 user defined weight

 ITU-R BT.709 (HDTV) as default(?)

convenience operator:
let value = color(0.5,0.5,0.1).gray

in the hope it will trickle into Pixie

**Comment by treeform** [comment]
Sorry, I don't understand what you mean here. I think you want to add another color mode?

**Comment by ingoogni** [comment]
Yes, indeed, a greyscale colour mode.

**Comment by treeform** [comment]
I don't have a need for a greyscale mode so I will not be adding one. But if you add it and submit a PR I will take it.

The main problem I see is that there are many ways to do the weights, its like which grayscale mode then?

**Comment by treeform** [comment]
I am going to close this because the it's not clear to me. Just use YUV and the Y for luminance for grayscale. No need for anything extra.
