### ISSUE TITLE
Create a tagged release

### ISSUE THREAD

**Issue by Calinou** [treeform/chroma#3]
I'm using this package in [clr](https://github.com/Calinou/clr) and would appreciate having a tagged release I could specify in my `.nimble` file (preferably following [Semantic Versioning](https://semver.org/)). I'm currently pinning a commit hash there, but it's better to rely on commits which are known to be stable and compatible :slightly_smiling_face:

**Comment by treeform** [comment]
I don't understand what a tagged release is needed? .nimble file already has versions is not not enough?

**Comment by treeform** [comment]
Sorry closing this. I still don't know what the benefit would be.

**Comment by Calinou** [comment]
According to its [README](https://github.com/nim-lang/nimble#versions), Nimble relies on Git tags for versions. This is why having tagged releases would be beneficial :slightly_smiling_face:

I apologize for not replying earlier — I get a lot of GitHub notifications and I end up missing some of them.
